### PR TITLE
Add fetch cache, support Italian and skip missing order type

### PR DESCRIPTION
**Pull request by httpiga**
I find your project very useful, while using it I made some changes you may be interested in:
- Apply Prettier: Feel free to rollback this one, I have it enabled by default in VS Code.
- Support Italian export when searching for fee description.
- The script is very slow when querying my local instance of Ghostfolio; I added a naive cache to speed up the ticker query.
- For some reason, in the export I used there were two subsequent fee entries, preventing the script to identify the respective buy/sell entry and leaving the fee entry without an order type. I was fine with just skipping it since it was a 0.01€ fee, feel free to remove this one if you think it doesn't fit the script logic.

### CODE REVIEW

**Comment by dickwolff** [comment]
Thanks for your PR, very much appreciated! I will try to take a look at it this weekend.

**Comment by dickwolff** [comment]
Which version of Ghostfolio are you using @httpiga? I just updated to 2.6.0 myself and the performance of API calls to Ghostfolio just plumetted. Previously I could process 120-ish records (with the Trading 212 export tool, which in essence is the same script as here) in 30-40 seconds. This was on version 1.293. Now with 2.6 the performance is nothing like before, I'm 5-7 minutes in and still only on record 26.

Taking all this into account, when using Ghostfolio pre 2.0, the app used to be "lightning" quick, but now it isn't anymore and this places your cache solution in aother perspective.

**Comment by httpiga** [comment]
@dickwolff I used your script only with Ghostfolio v2.6.0 and I confirm the very long execution times of the script. I tried to troubleshoot it and it seems that after some quick queries, one hangs for about 1 minute, another some quick queries and 1 minute wait again. I suspect that's some anti-DOS / anti-scraping measure from Ghostfolio or from some data providers (like Yahoo Finance).

An unrelated question I wanted to ask you: have you considered integrating your solution within Ghostfolio itself? I think they could appreciate a PR!

**Comment by dickwolff** [comment]
Thanks for your explanation. I have contacted Thomas from Ghostfolio and asked if he could explain the difference in performance. It is possible there have been some changes regarding the Yahoo Finance integration. I will await his response.

As to integrating within Ghostfolio; this was my original request to Thomas (started with Trading 212, and then DEGIRO also seemed useful), but Thomas stated that this was not part of the core functionality of Ghostfolio and suggested to create a separate converter script.

I am leaning to merging my Ghostfolio/Trading 212 scripts into one repository, because most of the code is the same (the looping, Ghostfolio data, etc) and create a separate convertor class for each source.

**Comment by dickwolff** [comment]
I cherry picked your changes to a [separate PR](https://github.com/dickwolff/DEGIRO-to-Ghostfolio/pull/6). Could you verify if this still achieves the results you have with your own code?

**Comment by httpiga** [comment]
> I am leaning to merging my Ghostfolio/Trading 212 scripts into one repository, because most of the code is the same (the looping, Ghostfolio data, etc) and create a separate convertor class for each source.

I agree, a modularised approach can make it easier also for additional contributors to add other brokers! 

> As to integrating within Ghostfolio; this was my original request to Thomas (started with Trading 212, and then DEGIRO also seemed useful), but Thomas stated that this was not part of the core functionality of Ghostfolio and suggested to create a separate converter script.

Too bad, I would have really appreciated it instead.

**Comment by dickwolff** [comment]
I have since moved the Trading 212 exporter to a generic solution. As soon as you have verified DEGIRO is in a working state, I will also move that one. Thanks!

For reference, here is the [new repo](https://github.com/dickwolff/Export-To-Ghostfolio). I plan to implement caching there, also.

**Comment by dickwolff** [comment]
Closing this since the tool has been moved. Suggested feedback has been taken into account in the new tool, now using more extensive caching and retrieving dat from Yahoo Finance directly instead of Ghostfolio, improving overall performance drastically.

Pre-build of the new tool can be found [here](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Retrieve-From-Yahoo-Finance)

**Pull request closed without merging**
